### ISSUE TITLE
BUG: audit rules are ignored when loading them at boot

### ISSUE THREAD

**Issue by frankm773** [linux-audit/audit-kernel#135] opened 2022-03-20 14:51 UTC
Running audit 3.0.7 with the following rules, will result in some rules getting ignored.
(This issue has been reproduced on several systems running archlinux and debian testing)

/etc/auditd/rules.d/audit.rules

```
# Delete all previous rules
-D

# Set buffer size
-b 8192

# test1
-w /usr/local/testfile -k  test1

# test2
-w /root/testfile -k test2

# test3
-w /etc/testfile -k test3

# test4
-w /home/testfile -k test4
```

auditctl -l
```
-w /usr/local/testfile -p rwxa -k test1
-w /root/testfile -p rwxa -k test2
-w /etc/testfile -p rwxa -k test3
-w /home/testfile -p rwxa -k test4
```

open the monitored files, add a character and save
```
nano /usr/local/testfile
nano /root/testfile
nano /etc/testfile
nano /home/testfile
```

resulting audit.log
```
time->Sun Mar 20 12:50:29 2022
type=PROCTITLE msg=audit(1647777029.223:58): proctitle=6E616E6F002F7573722F6C6F63616C2F7465737466696C65
type=PATH msg=audit(1647777029.223:58): item=1 name="/usr/local/testfile" inode=1205640 dev=08:03 mode=0100600 ouid=0 ogid=0 rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1647777029.223:58): item=0 name="/usr/local/" inode=1179649 dev=08:03 mode=040755 ouid=0 ogid=0 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1647777029.223:58): cwd="/root"
type=SYSCALL msg=audit(1647777029.223:58): arch=c000003e syscall=257 success=yes exit=3 a0=ffffff9c a1=6a35f6cbe80 a2=241 a3=1b6 items=2 ppid=1577 pid=1760 auid=1002 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=1 comm="nano" exe="/usr/bin/nano" key="test1"
----
time->Sun Mar 20 12:50:58 2022
type=PROCTITLE msg=audit(1647777058.868:59): proctitle=6E616E6F002F6574632F7465737466696C65
type=PATH msg=audit(1647777058.868:59): item=1 name="/etc/testfile" inode=1332 dev=08:02 mode=0100600 ouid=0 ogid=0 rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1647777058.868:59): item=0 name="/etc/" inode=14 dev=08:02 mode=040755 ouid=0 ogid=0 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1647777058.868:59): cwd="/root"
type=SYSCALL msg=audit(1647777058.868:59): arch=c000003e syscall=257 success=yes exit=3 a0=ffffff9c a1=43b5bc63860 a2=241 a3=1b6 items=2 ppid=1577 pid=1826 auid=1002 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=1 comm="nano" exe="/usr/bin/nano" key="test3"
```

When I ran 'auditctl -D' and then add the rules with 'auditctl -w /usr/local/testfile -k test1', 'auditctl -w /root/testfile -k test2'  and so on, all file access events (test1, test2, test3, test4) are logged as expected.

There are no audit errors in the log during bootup

When I reproduced these steps on debian stable (bullseye) with audit 3.0, all testfiles were logged correctly.

edit:
The affected kernel version on arch and Debian testing is 5.15.27 (arch) and 5.16 (Debian)
Unaffected is kernel 5.10.103-1 (Debian stable)

**Comment by frankm773** [comment] 2022-03-21 15:37
> Hi @frankm773,
> 
> It looks like you have used a variety of kernels and audit userspace version. If you use a modern, unpatched upstream kernel and a modern, unpatched audit userspace do you still see the same problem?

If I am not mistaken, the default kernel in arch is basically the vanilla kernel [1] and the audit userspace version appears to be unmodified as well [2]

[1] https://github.com/archlinux/svntogit-packages/tree/packages/linux/trunk
[2] https://github.com/archlinux/svntogit-packages/blob/packages/audit/trunk/PKGBUILD


I will compile the current upstream kernel and test it again if that helps.

**Comment by pcmoore** [comment] 2022-03-21 16:21
Yes, that would be helpful, thank you.

**Comment by frankm773** [comment] 2022-03-21 20:37
After compiling the current kernel 5.17 (2022-03-20) from kernel.org, I was able to reproduce the bug on that version as well

I have created a detailed reproduction log here:
https://gist.github.com/frankm773/54ee67c17699990ff45a5e42fbb0c074

**Comment by pcmoore** [comment] 2022-03-21 21:45
Thanks @frankm773, I did a quick test using your reproducer and it looks like it is working for me:
```
% uname -a
Linux dev-rawhide-1.lan 5.17.0-128.1.secnext.fc37.x86_64 #1 SMP PREEMPT Mon Mar 21 08:36:46 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
% rpm -q audit
audit-3.0.7-3.fc37.x86_64
%
% auditctl -D
No rules
% auditctl -w /usr/local/testfile -k test1
% auditctl -w /root/testfile -k test2
% auditctl -w /etc/testfile -k test3
% auditctl -w /home/testfile -k test4
% auditctl -l
-w /usr/local/testfile -p rwxa -k test1
-w /root/testfile -p rwxa -k test2
-w /etc/testfile -p rwxa -k test3
-w /home/testfile -p rwxa -k test4
%
% echo teststring >> /etc/testfile
% echo teststring >> /usr/local/testfile
% echo teststring >> /home/testfile
% echo teststring >> /root/testfile
%
% ausearch -i -k test1
----
type=PROCTITLE msg=audit(03/21/2022 17:38:59.888:397) : proctitle=auditctl -w /usr/local/testfile -k test1 
type=SYSCALL msg=audit(03/21/2022 17:38:59.888:397) : arch=x86_64 syscall=sendto success=yes exit=1080 a0=0x4 a1=0x7ffd116e67b0 a2=0x438 a3=0x0 items=0 ppid=1252 pid=1352 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=auditctl exe=/usr/sbin/auditctl subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null) 
type=CONFIG_CHANGE msg=audit(03/21/2022 17:38:59.888:397) : auid=root ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op=add_rule key=test1 list=exit res=yes 
----
type=PROCTITLE msg=audit(03/21/2022 17:39:58.456:402) : proctitle=-bash 
type=PATH msg=audit(03/21/2022 17:39:58.456:402) : item=1 name=/usr/local/testfile inode=5111901 dev=fc:04 mode=file,644 ouid=root ogid=root rdev=00:00 obj=unconfined_u:object_r:usr_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=PATH msg=audit(03/21/2022 17:39:58.456:402) : item=0 name=/usr/local/ inode=5112077 dev=fc:04 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:usr_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/21/2022 17:39:58.456:402) : cwd=/root 
type=SYSCALL msg=audit(03/21/2022 17:39:58.456:402) : arch=x86_64 syscall=openat success=yes exit=3 a0=AT_FDCWD a1=0x55c89f265e00 a2=O_WRONLY|O_CREAT|O_APPEND a3=0x1b6 items=2 ppid=1251 pid=1252 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=bash exe=/usr/bin/bash subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=test1 
% 
% ausearch -i -k test2
----
type=PROCTITLE msg=audit(03/21/2022 17:39:07.250:398) : proctitle=auditctl -w /root/testfile -k test2 
type=PATH msg=audit(03/21/2022 17:39:07.250:398) : item=0 name=/root/ inode=5242881 dev=fc:04 mode=dir,550 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:admin_home_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/21/2022 17:39:07.250:398) : cwd=/root 
type=SOCKADDR msg=audit(03/21/2022 17:39:07.250:398) : saddr={ saddr_fam=netlink nlnk-fam=16 nlnk-pid=0 } 
type=SYSCALL msg=audit(03/21/2022 17:39:07.250:398) : arch=x86_64 syscall=sendto success=yes exit=1076 a0=0x4 a1=0x7ffc76e056a0 a2=0x434 a3=0x0 items=1 ppid=1252 pid=1354 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=auditctl exe=/usr/sbin/auditctl subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null) 
type=CONFIG_CHANGE msg=audit(03/21/2022 17:39:07.250:398) : auid=root ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op=add_rule key=test2 list=exit res=yes 
----
type=PROCTITLE msg=audit(03/21/2022 17:40:15.109:404) : proctitle=-bash 
type=PATH msg=audit(03/21/2022 17:40:15.109:404) : item=1 name=/root/testfile inode=5243445 dev=fc:04 mode=file,644 ouid=root ogid=root rdev=00:00 obj=unconfined_u:object_r:admin_home_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=PATH msg=audit(03/21/2022 17:40:15.109:404) : item=0 name=/root/ inode=5242881 dev=fc:04 mode=dir,550 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:admin_home_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/21/2022 17:40:15.109:404) : cwd=/root 
type=SYSCALL msg=audit(03/21/2022 17:40:15.109:404) : arch=x86_64 syscall=openat success=yes exit=3 a0=AT_FDCWD a1=0x55c89f265040 a2=O_WRONLY|O_CREAT|O_APPEND a3=0x1b6 items=2 ppid=1251 pid=1252 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=bash exe=/usr/bin/bash subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=test2 
% 
% ausearch -i -k test3
----
type=PROCTITLE msg=audit(03/21/2022 17:39:15.966:399) : proctitle=auditctl -w /etc/testfile -k test3 
type=PATH msg=audit(03/21/2022 17:39:15.966:399) : item=0 name=/etc/ inode=4194305 dev=fc:04 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:etc_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/21/2022 17:39:15.966:399) : cwd=/root 
type=SOCKADDR msg=audit(03/21/2022 17:39:15.966:399) : saddr={ saddr_fam=netlink nlnk-fam=16 nlnk-pid=0 } 
type=SYSCALL msg=audit(03/21/2022 17:39:15.966:399) : arch=x86_64 syscall=sendto success=yes exit=1076 a0=0x4 a1=0x7ffceac3fde0 a2=0x434 a3=0x0 items=1 ppid=1252 pid=1356 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=auditctl exe=/usr/sbin/auditctl subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null) 
type=CONFIG_CHANGE msg=audit(03/21/2022 17:39:15.966:399) : auid=root ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op=add_rule key=test3 list=exit res=yes 
----
type=PROCTITLE msg=audit(03/21/2022 17:39:47.800:401) : proctitle=-bash 
type=PATH msg=audit(03/21/2022 17:39:47.800:401) : item=1 name=/etc/testfile inode=4194981 dev=fc:04 mode=file,644 ouid=root ogid=root rdev=00:00 obj=unconfined_u:object_r:etc_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=PATH msg=audit(03/21/2022 17:39:47.800:401) : item=0 name=/etc/ inode=4194305 dev=fc:04 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:etc_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/21/2022 17:39:47.800:401) : cwd=/root 
type=SYSCALL msg=audit(03/21/2022 17:39:47.800:401) : arch=x86_64 syscall=openat success=yes exit=3 a0=AT_FDCWD a1=0x55c89f265040 a2=O_WRONLY|O_CREAT|O_APPEND a3=0x1b6 items=2 ppid=1251 pid=1252 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=bash exe=/usr/bin/bash subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=test3 
% 
% ausearch -i -k test4
----
type=PROCTITLE msg=audit(03/21/2022 17:39:20.520:400) : proctitle=auditctl -w /home/testfile -k test4 
type=PATH msg=audit(03/21/2022 17:39:20.520:400) : item=0 name=/home/ inode=1048577 dev=fc:04 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:home_root_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/21/2022 17:39:20.520:400) : cwd=/root 
type=SOCKADDR msg=audit(03/21/2022 17:39:20.520:400) : saddr={ saddr_fam=netlink nlnk-fam=16 nlnk-pid=0 } 
type=SYSCALL msg=audit(03/21/2022 17:39:20.520:400) : arch=x86_64 syscall=sendto success=yes exit=1076 a0=0x4 a1=0x7fffe0791290 a2=0x434 a3=0x0 items=1 ppid=1252 pid=1358 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=auditctl exe=/usr/sbin/auditctl subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null) 
type=CONFIG_CHANGE msg=audit(03/21/2022 17:39:20.520:400) : auid=root ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 op=add_rule key=test4 list=exit res=yes 
----
type=PROCTITLE msg=audit(03/21/2022 17:40:09.179:403) : proctitle=-bash 
type=PATH msg=audit(03/21/2022 17:40:09.179:403) : item=1 name=/home/testfile inode=1048591 dev=fc:04 mode=file,644 ouid=root ogid=root rdev=00:00 obj=unconfined_u:object_r:home_root_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=PATH msg=audit(03/21/2022 17:40:09.179:403) : item=0 name=/home/ inode=1048577 dev=fc:04 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:home_root_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/21/2022 17:40:09.179:403) : cwd=/root 
type=SYSCALL msg=audit(03/21/2022 17:40:09.179:403) : arch=x86_64 syscall=openat success=yes exit=3 a0=AT_FDCWD a1=0x55c89f2f0920 a2=O_WRONLY|O_CREAT|O_APPEND a3=0x1b6 items=2 ppid=1251 pid=1252 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts0 ses=3 comm=bash exe=/usr/bin/bash subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=test4
```

**Comment by frankm773** [comment] 2022-03-21 22:57
The issue only appears when the rules are added via audit.rules file, not when done manually

Rules added via auditctl are always logged correctly.

Have you tried to reproduce it via rules file as well?


Reproducing the bug

1. edit /etc/auditd/rules.d/audit.rules
```
# Delete all previous rules
-D
# Set buffer size
-b 8192
# test1
-w /usr/local/testfile -k  test1
# test2
-w /root/testfile -k test2
# test3
-w /etc/testfile -k test3
# test4
-w /home/testfile -k test4
```

2. reboot

3. write to /root/testfile

4. read audit.log to verify test2


Note: Running either 'auditctl -w NEWRULE' or 'augenrules --load' will result in the rules being applied correctly
The bug seems to only appear after a reboot (even if the rules were not modified)

**Comment by stevegrubb** [comment] 2022-03-22 02:03
Do you boot with audit=1 as a kernel boot parameter? Do the rules appear correct with auditctl -l after boot? Do all the files exist prior to the rules being loaded or do you create all or some of them when you edit with nano?

**Comment by frankm773** [comment] 2022-03-22 10:53
> Do you boot with audit=1 as a kernel boot parameter? 

No, that kernel parameter is neither set on the affected system nor is it set on the unaffected debian stable (bullseye) where the files are logged correctly.


> Do the rules appear correct with auditctl -l after boot? 

Yes, 
Output of auditctl -l

```
-w /usr/local/testfile -p rwxa -k test1
-w /root/testfile -p rwxa -k test2
-w /etc/testfile -p rwxa -k test3
-w /home/testfile -p rwxa -k test4
```


> Do all the files exist prior to the rules being loaded or do you create all or some of them when you edit with nano?

I have tested both scenarios with the same result. Test 2 and test4 are never logged unless the rules are reinitialized as described

**Comment by pcmoore** [comment] 2022-03-23 18:08
@frankm773 no, not yet.  I suspect this may be an issue with the userspace or how the userspace is started (is systemd doing something odd?).  From a kernel perspective there shouldn't be anything different from using auditctl to load rules interactively vs loading them via init/systemd/etc. at boot.

**Comment by pcmoore** [comment] 2022-03-23 18:19
I don't know what to tell you @frankm773, it works for me ... ?
```
% uname -a
Linux dev-rawhide-1.lan 5.17.0-128.2.secnext.fc37.x86_64 #1 SMP PREEMPT Mon Mar 21 14:34:12 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
% rpm -q audit
audit-3.0.7-3.fc37.x86_64
% 
% auditctl -l
-w /usr/local/testfile -p rwxa -k test1
-w /root/testfile -p rwxa -k test2
-w /etc/testfile -p rwxa -k test3
-w /home/testfile -p rwxa -k test4
% 
% cat /etc/audit/rules.d/gh-135.rules 
# https://github.com/linux-audit/audit-kernel/issues/135

-w /usr/local/testfile -p rwxa -k test1
-w /root/testfile -p rwxa -k test2
-w /etc/testfile -p rwxa -k test3
-w /home/testfile -p rwxa -k test4

% cat /etc/audit/audit.rules
## This file is automatically generated from /etc/audit/rules.d
-D


-w /usr/local/testfile -p rwxa -k test1
-w /root/testfile -p rwxa -k test2
-w /etc/testfile -p rwxa -k test3
-w /home/testfile -p rwxa -k test4

% 
% echo "works for me" >> /etc/testfile
% 
% ausearch -i -k test3
----
type=PROCTITLE msg=audit(03/23/2022 14:15:19.032:151) : proctitle=/sbin/auditctl -R /etc/audit/audit.rules 
type=PATH msg=audit(03/23/2022 14:15:19.032:151) : item=0 name=/etc/ inode=4194305 dev=fc:04 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:etc_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/23/2022 14:15:19.032:151) : cwd=/ 
type=SOCKADDR msg=audit(03/23/2022 14:15:19.032:151) : saddr={ saddr_fam=netlink nlnk-fam=16 nlnk-pid=0 } 
type=SYSCALL msg=audit(03/23/2022 14:15:19.032:151) : arch=x86_64 syscall=sendto success=yes exit=1076 a0=0x3 a1=0x7ffc9ee0a9e0 a2=0x434 a3=0x0 items=1 ppid=652 pid=667 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=auditctl exe=/usr/sbin/auditctl subj=system_u:system_r:unconfined_service_t:s0 key=(null) 
type=CONFIG_CHANGE msg=audit(03/23/2022 14:15:19.032:151) : auid=unset ses=unset subj=system_u:system_r:unconfined_service_t:s0 op=add_rule key=test3 list=exit res=yes 
----
type=PROCTITLE msg=audit(03/23/2022 14:17:35.176:325) : proctitle=-bash 
type=PATH msg=audit(03/23/2022 14:17:35.176:325) : item=1 name=/etc/testfile inode=4195330 dev=fc:04 mode=file,644 ouid=root ogid=root rdev=00:00 obj=unconfined_u:object_r:etc_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=PATH msg=audit(03/23/2022 14:17:35.176:325) : item=0 name=/etc/ inode=4194305 dev=fc:04 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:etc_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/23/2022 14:17:35.176:325) : cwd=/root 
type=SYSCALL msg=audit(03/23/2022 14:17:35.176:325) : arch=x86_64 syscall=openat success=yes exit=3 a0=AT_FDCWD a1=0x55eb11fbbcf0 a2=O_WRONLY|O_CREAT|O_APPEND a3=0x1b6 items=2 ppid=892 pid=893 auid=root uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts1 ses=3 comm=bash exe=/usr/bin/bash subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=test3
%
```

**Comment by frankm773** [comment] 2022-03-23 19:06
@pcmoore Sorry about the confusion, I realise this bugreport is not described very clearly

The bug I have observed on my system (as well as on several test VMs) ignores **some** audit rules depending on the path (and only if the rules are not reinitialized after bootup)

In the described reproduction experiment, test1 and test3 are logged correctly but test2 and test4 are ignored.

The audit rules are setup to log all file access to those 4 testcases but the cases accessing files on /root and /home are not logged. 

Hope this helps clear things up a bit.

**Comment by pcmoore** [comment] 2022-03-23 20:20
Oh, if you are only having problems with "/root/testfile" and "/home/testfile" this is NOTABUG with the kernel, it's a bug (feature?) of the systemd unit file which loads the rules and starts auditd at boot.  For example on my Rawhide system we see the following:
```
% cat /usr/lib/systemd/system/auditd.service
[Unit]
Description=Security Auditing Service
DefaultDependencies=no
## If auditd is sending or recieving remote logging, copy this file to
## /etc/systemd/system/auditd.service and comment out the first After and
## uncomment the second so that network-online.target is part of After.
## then comment the first Before and uncomment the second Before to remove
## sysinit.target from "Before".
After=local-fs.target systemd-tmpfiles-setup.service
##After=network-online.target local-fs.target systemd-tmpfiles-setup.service
Before=sysinit.target shutdown.target
##Before=shutdown.target
Conflicts=shutdown.target
RefuseManualStop=yes
ConditionKernelCommandLine=!audit=0
Documentation=man:auditd(8) https://github.com/linux-audit/audit-documentation

[Service]
Type=forking
PIDFile=/run/auditd.pid
ExecStart=/sbin/auditd
## To not use augenrules, copy this file to /etc/systemd/system/auditd.service
## and comment/delete the next line and uncomment the auditctl line.
## NOTE: augenrules expect any rules to be added to /etc/audit/rules.d/
ExecStartPost=-/sbin/augenrules --load
#ExecStartPost=-/sbin/auditctl -R /etc/audit/audit.rules
# By default we don't clear the rules on exit. To enable this, uncomment
# the next line after copying the file to /etc/systemd/system/auditd.service
#ExecStopPost=/sbin/auditctl -R /etc/audit/audit-stop.rules
Restart=on-failure
# Do not restart for intentional exits. See EXIT CODES section in auditd(8).
RestartPreventExitStatus=2 4 6

### Security Settings ###
MemoryDenyWriteExecute=true
LockPersonality=true
ProtectControlGroups=true
ProtectKernelModules=true
ProtectHome=true
RestrictRealtime=true

[Install]
WantedBy=multi-user.target
```

... note the `ProtectHome=true` line in the configuration above.  If we look at the `systemd.exec(5)` manpage we see the following explanation of this setting:
```
ProtectHome=
Takes a boolean argument or the special values "read-only" or "tmpfs". If true, the directories /home/,
/root, and /run/user are made inaccessible and empty for processes invoked by this unit. If set to
"read-only", the three directories are made read-only instead. If set to "tmpfs", temporary file systems
are mounted on the three directories in read-only mode. The value "tmpfs" is useful to hide home
directories not relevant to the processes invoked by the unit, while still allowing necessary directories
to be made visible when listed in BindPaths= or BindReadOnlyPaths=.

Setting this to "yes" is mostly equivalent to set the three directories in InaccessiblePaths=. Similarly,
"read-only" is mostly equivalent to ReadOnlyPaths=, and "tmpfs" is mostly equivalent to
TemporaryFileSystem= with ":ro".

It is recommended to enable this setting for all long-running services (in particular network-facing
ones), to ensure they cannot get access to private user data, unless the services actually require
access to the user's private data. This setting is implied if DynamicUser= is set. This setting
cannot ensure protection in all cases. In general it has the same limitations as ReadOnlyPaths=,
see below.

This option is only available for system services and is not supported for services running in
per-user instances of the service manager.
```

What is happening is that when you load an audit rule to watch a file like you are doing here, the kernel leverages some internal functionality to "tag" the file so that the audit subsystem is notified when it is accessed.  With the systemd config above the "/home" and "/root" directories are not the same between when the audit rules are loaded and when the system is available for interactive use.  If you want to set audit rules on "/home" or "/root" you will need to change this systemd setting for the auditd service on your system.

Unfortunately there is nothing the kernel can do here; closing as NOTABUG.

**Closed by pcmoore** 2022-03-23 20:20 UTC
Labels: bug, priority/medium

**Comment by frankm773** [comment] 2022-03-23 20:55
Thank you for the explanation and your time to look at it.

**Comment by stevegrubb** [comment] 2022-03-26 15:11
There have been many people asking to use more and more systemd protections because "systemd-analyze security" tells them the service is insecure - for example, PR 228 and several more before that. I guess this got in there during one of the PR's to add hardening. I fixed this in the auditd.service file.

**Comment by pcmoore** [comment] 2022-03-26 21:08
@stevegrubb did you want me to transfer this to the audit-userspace project so you have a record of this?

**Comment by stevegrubb** [comment] 2022-03-27 13:40
Sure
