### ISSUE TITLE
RFE: improved SECCOMP record filtering

### ISSUE THREAD

**Issue by stevegrubb** [linux-audit/audit-kernel#71] opened 2018-01-02 23:10 UTC
The seccomp trap event is probably not suitable to log by default. I think people are writing some supervisor process that inspects process integrity before allowing it to proceed. This means you can get 10's of thousands of events a day drowning out everything in the logs. In contrast errno returns make well behaved program exit or otherwise stop accessing something. Same thing with terminating a process.

We need some way to limit the logging of seccomp events. Or make applications specifically enable auditing when a trap action is asked for. It should default to no logging.

**Comment by pcmoore** [comment] 2018-01-03 14:27
I'm changing the issue title to make this a more generic SECCOMP record filtering issue.

**Comment by pcmoore** [comment] 2018-01-29 08:40
Closing as a duplicate of issue #13

**Closed by pcmoore** 2018-01-29 08:40 UTC
Labels: enhancement, priority/medium
