### ISSUE TITLE
Q: unknown AUDIT_NETFILTER_CFG events

### ISSUE THREAD

**Issue by stevegrubb** [linux-audit/audit-kernel#25] opened 2016-11-20 18:51 UTC
Almost all AUDIT_NETFILTER_CFG events have a syscall and proctitle record. Every now and then we get an event like this:

type=NETFILTER_CFG msg=audit(1479622038.866:2): table=filter family=2 entries=0

and that is all there is. I have no idea what this event means or why it was emitted.

**Comment by stevegrubb** [comment] 2016-11-21 16:26
While this may be formulated as a question, events are supposed to have a purpose that is related to the security posture of the system. To be well-formed, they must include a subject, object, action, and results. By attaching a syscall record, the event satisfies the well-formedness. If this is not initiated by a syscall, then we might consider a new event type and fields added to make it well formed.

**Comment by pcmoore** [comment] 2016-11-21 20:53
I think the first step is to understand what system event causes this record to be created, then we can sort out what we should be doing from an audit perspective.  This is why I marked this as Q/question; we don't know if it is a problem yet or not, we need to investigate further.

**Comment by rgbriggs** [comment] 2017-05-16 19:33
Findings:

- At least the following list of events trigger NETFILTER_CFG records (There may be more events that will trigger this message type.):
  - init_module, finit_module: modprobe
  - setsockopt: iptables-restore, ip6tables-restore, ebtables-restore
  - unshare: (h?)ostnamed
  - clone: libvirtd

- The syscall events unsolicited by any audit rule are caused by a missing !audit_dummy_context() check before creating a NETFILTER_CFG record.

- The vast majority of unaccompanied records are caused by the fedora default rule: "-a never,task" and the occasional early startup one is I believe caused by the iptables filter hard linked into the kernel rather than a module.

- Seemingly duplicate records are not actually duplicates that are caused by netfilter table initialization in different network namespaces from the same syscall.

- Ebtables module initialization to register tables doesn't generate records because it was never hooked in to audit.

**Comment by pcmoore** [comment] 2017-05-16 21:27
> The syscall events unsolicited by any audit rule are caused by a missing !audit_dummy_context() check before creating a NETFILTER_CFG record. Check !audit_dummy_context() before creating the NETFILTER_CFG record.

Ah, good.  Mystery solved.

> Seemingly duplicate records are not actually exact duplicates that are caused by netfilter table initialization in different network namespaces from the same syscall. Recommend adding the network namespace ID (proc inode) to the record to make this obvious.

Let's hold off on the namespace ID bits for this specific record until we figure out the greater problem of how we want to track/mark events with namespace info.

> Ebtables module initialization to register tables doesn't generate records because it was never hooked in to audit. Recommend adding audit hooks to log this.

Seems reasonable to me.

**Comment by rgbriggs** [comment] 2017-05-18 18:02
Posted RFC patchset upstream:
https://www.redhat.com/archives/linux-audit/2017-May/msg00034.html
http://marc.info/?l=netfilter-devel&m=149512814901358&w=2
http://marc.info/?l=netfilter-devel&m=149512820601374&w=2
http://marc.info/?l=netfilter-devel&m=149512821101377&w=2
http://marc.info/?l=netfilter-devel&m=149512823001388&w=2

**Comment by rgbriggs** [comment] 2017-05-18 18:42
Better netfilter-devel archives link (though slower to propagate):
http://www.spinics.net/lists/netfilter-devel/msg47986.html

**Comment by rgbriggs** [comment] 2020-01-06 23:25
post v2
        https://www.redhat.com/archives/linux-audit/2020-January/msg00006.html
        https://lkml.org/lkml/2020/1/6/557

**Comment by rgbriggs** [comment] 2020-04-22 22:14
post v4
https://www.redhat.com/archives/linux-audit/2020-April/msg00120.html
https://lkml.org/lkml/2020/4/22/1776

**Comment by rgbriggs** [comment] 2020-05-19 15:38
post v5
https://www.redhat.com/archives/linux-audit/2020-May/msg00063.html
https://lkml.org/lkml/2020/5/19/665

userspace to parse yaasao for EVENT_LISTENER and NETFILTER_CFG:
https://www.redhat.com/archives/linux-audit/2020-May/msg00064.html
    https://www.redhat.com/archives/linux-audit/2020-May/msg00065.html
    https://www.redhat.com/archives/linux-audit/2020-May/msg00066.html

**Comment by rgbriggs** [comment] 2020-05-20 19:11
post v6
https://www.redhat.com/archives/linux-audit/2020-May/msg00071.html
https://lkml.org/lkml/2020/5/20/1048

self-NACK:
https://www.redhat.com/archives/linux-audit/2020-May/msg00075.html
https://lkml.org/lkml/2020/5/20/1053

post v6 userspace
https://www.redhat.com/archives/linux-audit/2020-May/msg00072.html

post v6a
https://www.redhat.com/archives/linux-audit/2020-May/msg00077.html
https://lkml.org/lkml/2020/5/20/1235

**Comment by rgbriggs** [comment] 2020-05-20 22:45
v6a upstreamed 9d44a121c5a7 ("audit: add subj creds to NETFILTER_CFG record to...")

**Comment by rgbriggs** [comment] 2020-12-16 22:44
This can be closed since it is upstream in v5.8-rc1
c4dad0aab3fc  ("audit: tidy and extend netfilter_cfg x_tables")
a45d88530b25  ("netfilter: add audit table unregister actions")
db9ff6ecf6ef  ("audit: make symbol 'audit_nfcfgs' static")
9d44a121c5a7  ("audit: add subj creds to NETFILTER_CFG record to")
Note: the usespace parser didn't make it into audit-3.0 (patches were on mailing list months ago, a PR has since been issued)

**Closed** 2020-12-17 02:27 UTC
Labels: priority/low, question
