### ISSUE TITLE
RFE: NETFILTER_CFG event cleanup

### ISSUE THREAD

**Issue by stevegrubb** [linux-audit/audit-kernel#58] opened 2017-07-26 14:13 UTC
This event should be a simple record with the following fields: pid, uid, auid, tty, session, context, comm, exe (in this order) + old value + new value if applicable.

**Comment by rgbriggs** [comment] 2017-08-02 06:25
This is a duplicate of https://github.com/linux-audit/audit-kernel/issues/35

**Comment by pcmoore** [comment] 2017-08-02 21:19
> This is a duplicate of #35

I made mention of @stevegrubb's request in #35, so lets close this out and continue to track this RFE in #35.

**Closed by pcmoore** 2017-08-02 21:19 UTC
Labels: enhancement, priority/low
